/*
 * config_v7.h
 *
 *  Created on: 2017Äê8ÔÂ17ÈÕ
 *      Author: Administrator
 */

#ifndef CONFIG_V7_H_
#define CONFIG_V7_H_

#include "xparameters.h"

typedef unsigned int u32;
typedef unsigned char u8;

//#define MACROCONNECT(a,b) a##b

#define XPAR_V7_CFG_FIFO0_BASEADDR XPAR_V7_CFG_FIFO0_BASEADDR
#define XPAR_V7_CFG_FIFO1_BASEADDR XPAR_V7_CFG_FIFO1_BASEADDR
#define XPAR_V7_CFG_FIFO2_BASEADDR XPAR_V7_CFG_FIFO2_BASEADDR
#define XPAR_V7_CFG_FIFO3_BASEADDR XPAR_V7_CFG_FIFO3_BASEADDR

#define FIFO_ISR_ADDR0 XPAR_V7_CFG_FIFO0_BASEADDR
#define FIFO_ISR_ADDR1 XPAR_V7_CFG_FIFO1_BASEADDR
#define FIFO_ISR_ADDR2 XPAR_V7_CFG_FIFO2_BASEADDR
#define FIFO_ISR_ADDR3 XPAR_V7_CFG_FIFO3_BASEADDR

#define FIFO_IER_ADDR0 XPAR_V7_CFG_FIFO0_BASEADDR+0x4
#define FIFO_IER_ADDR1 XPAR_V7_CFG_FIFO1_BASEADDR+0x4
#define FIFO_IER_ADDR2 XPAR_V7_CFG_FIFO2_BASEADDR+0x4
#define FIFO_IER_ADDR3 XPAR_V7_CFG_FIFO3_BASEADDR+0x4

#define FIFO_TDFD_ADDR0 XPAR_V7_CFG_FIFO0_BASEADDR+0x10
#define FIFO_TDFD_ADDR1 XPAR_V7_CFG_FIFO1_BASEADDR+0x10
#define FIFO_TDFD_ADDR2 XPAR_V7_CFG_FIFO2_BASEADDR+0x10
#define FIFO_TDFD_ADDR3 XPAR_V7_CFG_FIFO3_BASEADDR+0x10

#define FIFO_TLR_ADDR0 XPAR_V7_CFG_FIFO0_BASEADDR+0x14
#define FIFO_TLR_ADDR1 XPAR_V7_CFG_FIFO1_BASEADDR+0x14
#define FIFO_TLR_ADDR2 XPAR_V7_CFG_FIFO2_BASEADDR+0x14
#define FIFO_TLR_ADDR3 XPAR_V7_CFG_FIFO3_BASEADDR+0x14

#define FIFO_TDR_ADDR0 XPAR_V7_CFG_FIFO0_BASEADDR+0x2C
#define FIFO_TDR_ADDR1 XPAR_V7_CFG_FIFO1_BASEADDR+0x2C
#define FIFO_TDR_ADDR2 XPAR_V7_CFG_FIFO2_BASEADDR+0x2C
#define FIFO_TDR_ADDR3 XPAR_V7_CFG_FIFO3_BASEADDR+0x2C

int Config_V7(unsigned int *src_addr, int data_size_byte);

int Config_V7_single(unsigned int *src_addr, int data_size_byte,unsigned int v7_select);

#endif /* CONFIG_V7_H_ */
